//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacevalackaAplikacija.Models.EFR
{
    using System;
    using System.Collections.Generic;
    
    public partial class FazaTakmicenja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FazaTakmicenja()
        {
            this.UcesnickiNalog = new HashSet<UcesnickiNalog>();
        }
    
        public int FazaTakmicenjaID { get; set; }
        public string NazivFaze { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UcesnickiNalog> UcesnickiNalog { get; set; }
    }
}
