//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacevalackaAplikacija.Models.EFR
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizatorskiNalog
    {
        public int OrganizatorskiNalogID { get; set; }
        public string ImePrezime { get; set; }
        public string Klub { get; set; }
        public string OrganizatorskiKod { get; set; }
    }
}
