//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacevalackaAplikacija.Models.EFR
{
    using System;
    using System.Collections.Generic;
    
    public partial class UcesnickiNalog
    {
        public int UcesnickiNalogID { get; set; }
        public string ImePrezime { get; set; }
        public string Klub { get; set; }
        public string Uloga { get; set; }
        public int DisciplinaID { get; set; }
        public int FazaTakmicenjaID { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual FazaTakmicenja FazaTakmicenja { get; set; }
    }
}
